public enum Ability
{
    None,
    Stench,
    Drizzle,
    SpeedBoost,
    BattleArmor,
    Sturdy,
    Damp,
    Limber,
    SandVeil,
    Static,
    VoltAbsorb,
    WaterAbsorb,
    Oblivious, //Not done
    CloudNine, 
    CompoundEyes,
    Insomnia,
    ColorChange, //Not done
    Immunity,
    FlashFire,
    ShieldDust, //Not done
    OwnTempo, //Not done
    SuctionCups,
    Intimidate,
    ShadowTag,
    RoughSkin, //Not done
    WonderGuard, //Not done
    Levitate,
    EffectSpore, //Not done
    Synchronize, //Not done
    ClearBody, //Not done
    NaturalCure, //Not done
    LightningRod, //Not done
    SereneGrace, //Not done
    SwiftSwim,
    Chlorophyll,
    Illuminate,
    Trace, //Not done
    HugePower, //Not done
    PoisonPoint, //Not done
    InnerFocus, //Not done
    MagmaArmor, //Not done
    WaterVeil, //Not done
    MagnetPull, //Not done
    Soundproof, //Not done
    RainDish, //Not done
    SandStream, //Not done
    Pressure, //Not done
    ThickFat, //Not done
    EarlyBird, //Not done
    FlameBody, //Not done
    RunAway, //Not done
    KeenEye, //Not done
    HyperCutter, //Not done
    Pickup, //Not done
    Truant, //Not done
    Hustle, //Not done
    CuteCharm, //Not done
    Plus, //Not done
    Minus, //Not done
    Forecast, //Not done
    StickyHold, //Not done
    ShedSkin, //Not done
    Guts, //Not done
    MarvelScale, //Not done
    LiquidOoze, //Not done
    Overgrow, //Not done
    Blaze, //Not done
    Torrent, //Not done
    Swarm, //Not done
    RockHead, //Not done
    Drought, //Not done
    ArenaTrap, //Not done
    VitalSpirit, //Not done
    WhiteSmoke, //Not done
    PurePower, //Not done
    ShellArmor, //Not done
    AirLock, //Not done
    TangledFeet, //Not done
    MotorDrive, //Not done
    Rivalry, //Not done
    Steadfast, //Not done
    SnowCloak, //Not done
    Gluttony, //Not done
    AngerPoint, //Not done
    Unburden, //Not done
    Heatproof, //Not done
    Simple, //Not done
    DrySkin, //Not done
    Download, //Not done
    IronFist, //Not done
    PoisonHeal, //Not done
    Adaptability, //Not done
    SkillLink, //Not done
    Hydration, //Not done
    SolarPower, //Not done
    QuickFeet, //Not done
    Normalize, //Not done
    Sniper, //Not done
    MagicGuard, //Not done
    NoGuard, //Not done
    Stall, //Not done
    Technician, //Not done
    LeafGuard, //Not done
    Klutz, //Not done
    MoldBreaker, //Not done
    SuperLuck, //Not done
    Aftermath, //Not done
    Anticipation, //Not done
    Forewarn, //Not done
    Unaware, //Not done
    TintedLens, //Not done
    Filter, //Not done
    SlowStart, //Not done
    Scrappy, //Not done
    StormDrain, //Not done
    IceBody, //Not done
    SolidRock, //Not done
    SnowWarning, //Not done
    HoneyGather, //Not done
    Frisk, //Not done
    Reckless, //Not done
    Multitype, //Not done
    FlowerGift, //Not done
    BadDreams, //Not done
    Pickpocket, //Not done
    SheerForce, //Not done
    Contrary, //Not done
    Unnerve, //Not done
    Defiant, //Not done
    Defeatist, //Not done
    CursedBody, //Not done
    Healer, //Not done
    FriendGuard, //Not done
    WeakArmor, //Not done
    HeavyMetal, //Not done
    LightMetal, //Not done
    Multiscale, //Not done
    ToxicBoost, //Not done
    FlareBoost, //Not done
    Harvest, //Not done
    Telepathy, //Not done
    Moody, //Not done
    Overcoat, //Not done
    PoisonTouch, //Not done
    Regenerator, //Not done
    BigPecks, //Not done
    SandRush,
    WonderSkin, //Not done
    Analytic, //Not done
    Illusion, //Not done
    Imposter, //Not done
    Infiltrator, //Not done
    Mummy, //Not done
    Moxie, //Not done
    Justified, //Not done
    Rattled, //Not done
    MagicBounce, //Not done
    SapSipper, //Not done
    Prankster, //Not done
    SandForce, //Not done
    IronBarbs, //Not done
    ZenMode, //Not done
    VictoryStar, //Not done
    Turboblaze, //Not done
    Teravolt, //Not done
    AromaVeil, //Not done
    FlowerVeil, //Not done
    CheekPouch, //Not done
    Protean, //Not done
    FurCoat, //Not done
    Magician, //Not done
    Bulletproof, //Not done
    Competitive, //Not done
    StrongJaw, //Not done
    Refrigerate, //Not done
    SweetVeil, //Not done
    StanceChange, //Not done
    GaleWings, //Not done
    MegaLauncher, //Not done
    GrassPelt, //Not done
    Symbiosis, //Not done
    ToughClaws, //Not done
    Pixilate, //Not done
    Gooey, //Not done
    Aerilate, //Not done
    ParentalBond, //Not done
    DarkAura, //Not done
    FairyAura, //Not done
    AuraBreak, //Not done
    PrimoridialSea, //Not done
    DesolateLand, //Not done
    DeltaStream, //Not done
    Stamina, //Not done
    WimpOut, //Not done
    EmergencyExit, //Not done
    WaterCompaction, //Not done
    Merciless, //Not done
    ShieldsDown, //Not done
    Stakeout, //Not done
    WaterBubble, //Not done
    Steelworker, //Not done
    Berserk, //Not done
    SlushRush,
    LongReach, //Not done
    LiquidVoice, //Not done
    Triage, //Not done
    Galvanize, //Not done
    SurgeSurfer, //Not done
    Schooling, //Not done
    Disguise, //Not done
    BattleBond, //Not done
    PowerConstruct, //Not done
    Corrosion, //Not done
    Comatose, //Not done
    QueenlyMajesty, //Not done
    InnardsOut, //Not done
    Dancer, //Not done
    Battery, //Not done
    Fluffy, //Not done
    Dazzling, //Not done
    SoulHeart, //Not done
    TanglingHair, //Not done
    Receiver, //Not done
    PowerOfAlchemy, //Not done
    BeastBoost, //Not done
    RKSSystem, //Not done
    ElectricSurge, //Not done
    PsychicSurge, //Not done
    MistySurge, //Not done
    GrassySurge, //Not done
    FullMetalBody, //Not done
    ShadowShield, //Not done
    PrismArmor, //Not done
    Neuroforce, //Not done
    IntrepidSword, //Not done
    DauntlessShield, //Not done
    Libero, //Not done
    BallFetch, //Not done
    CottonDown, //Not done
    PropellorTail, //Not done
    MirrorArmor, //Not done
    GulpMissile, //Not done
    Stalwart, //Not done
    SteamEngine, //Not done
    PunkRock, //Not done
    SandSpit, //Not done
    IceScales, //Not done
    Ripen, //Not done
    IceFace, //Not done
    PowerSpot, //Not done
    Mimicry, //Not done
    ScreenCleaner, //Not done
    SteelySpirit, //Not done
    PerishBody, //Not done
    WanderingSpirit, //Not done
    GorillaTactics, //Not done
    NeutralizingGas, //Not done
    PastelVeil, //Not done
    HungerSwitch, //Not done
    QuickDraw, //Not done
    UnseenFist, //Not done
    CuriousMedicine, //Not done
    Transistor, //Not done
    DragonsMaw, //Not done
    ChillingNeigh, //Not done
    GrimNeigh, //Not done
    AsOneGlastrier, //Not done
    AsOneSpectrier, //Not done
    LingeringAroma, //Not done
    SeedSower, //Not done
    ThermalExchange, //Not done
    AngerShell, //Not done
    PurifyingSalt, //Not done
    WellBakedBody, //Not done
    WindRider, //Not done
    GuardDog, //Not done
    RockyPayload, //Not done
    WindPower, //Not done
    ZeroToHero, //Not done
    Commander, //Not done
    Electromorphosis, //Not done
    Protosynthesis, //Not done
    QuarkDrive, //Not done
    GoodAsGold, //Not done
    VesselOfRuin, //Not done
    SwordOfRuin, //Not done
    TabletsOfRuin, //Not done
    BeadsOfRuin, //Not done
    OrichalcumPulse, //Not done
    HadronEngine, //Not done
    Opportunist, //Not done
    CudChew, //Not done
    Sharpness, //Not done
    SupremeOverlord, //Not done
    Costar, //Not done
    ToxicDebris, //Not done
    EarthEater, //Not done
    MyceliumMight, //Not done
    ToxicChain, //Not done
    SupersweetSyrup, //Not done
    Hospitality, //Not done

}