public enum ItemID
{
    None,
    //Berries
    OccaBerry,
    PasshoBerry,
    RindoBerry,
    WacanBerry,
    YacheBerry,
    ChopleBerry,
    KebiaBerry,
    ShucaBerry,
    CobaBerry,
    PayapaBerry,
    TangaBerry,
    ChartiBerry,
    KasibBerry,
    HabanBerry,
    ColburBerry,
    BabiriBerry,
    RoseliBerry,
    ChilanBerry,
    //Evolution items
    FireStone,
    WaterStone,
    ThunderStone,
    LeafStone,
    MoonStone,
    SunStone,
    ShinyStone,
    DuskStone,
    DawnStone,
    IceStone,
    //Held items
    KingsRock,
    MetalCoat,
    DeepSeaTooth,
    DeepSeaScale,
    //Abstract items
    DragonScale,
    PrismScale,
    UpGrade,
    //Mega stones
    Venusaurite,
    CharizarditeX,
    CharizarditeY,
    Blastoisinite,
    Beedrillite,
    Pidgeotite,
    Alakazite,
    Slowbronite,
    Gengarite,
    Kangaskhanite,
    Pinsirite,
    Gyaradosite,
    Aerodactylite,
    MewtwoniteX,
    MewtwoniteY,
    Ampharosite,
    Steelixite,
    Scizorite,
    Heracronite,
    Houndoominite,
    Tyranitarite,

    Count,
}