using static MoveEffect;
public enum MoveEffect : ushort
{
    //No added effect
    None,
    Hit,
    //Multi-hit moves
    MultiHit2,
    MultiHit2to5,
    DoubleIronBash,
    PopulationBomb,
    ScaleShot,
    MultiHit3,
    Twineedle,
    TripleHit,
    //Status-inducing moves
    Burn,
    Paralyze,
    Poison,
    Toxic,
    Freeze,
    Sleep,
    Confuse,
    TriAttack,
    Swagger,
    Flatter,
    DireClaw,
    //Stat changes
    AttackUp1,
    AttackUp2,
    DefenseUp1,
    DefenseUp2,
    DefenseUp3,
    SpAtkUp1,
    SpAtkUp2,
    SpAtkUp3,
    SpDefUp1,
    SpDefUp2,
    SpeedUp1,
    SpeedUp2,
    EvasionUp1,
    EvasionUp2,
    CritRateUp2,
    AttackDown1,
    AttackDown2,
    DefenseDown1,
    DefenseDown2,
    SpAtkDown1,
    SpAtkDown2,
    SpDefDown1,
    SpDefDown2,
    SpeedDown1,
    SpeedDown2,
    AccuracyDown1,
    EvasionDown2,
    AttackDefenseUp1,
    AttackSpAtkUp1,
    AttackSpeedUp1,
    AttackAccuracyUp1,
    DefenseSpDefUp1,
    SpAtkSpDefUp1,
    AttackDefenseDown1,
    AttackSpAtkDown1,
    DefenseSpDefDown1,
    AttackUp1SpeedUp2,
    AttackDefenseAccUp1,
    AttackDefenseSpeedUp1,
    SpAtkSpDefSpeedUp1,
    DefSpDefSpeedDown1,
    AttackSpAtkUp2,
    SpAtkSpDefSpeedUp2,
    AllUp1,
    AllUp2,
    Acupressure,
    Autotomize,
    BellyDrum,
    Captivate,
    Charge,
    ClangorousSoul,
    DefenseCurl,
    DiamondStorm,
    GearUp,
    HyperspaceFury,
    FlowerShield,
    Growth,
    MagneticFlux,
    Minimize,
    NoRetreat,
    Rototiller,
    ShellSmash,
    SpicyExtract,
    TarShot,
    TripleArrows,
    VenomDrench,
    //Other status moves
    AfterYou,
    Attract,
    Bestow,
    CourtChange,
    Curse,
    Defog,
    Disable,
    Doodle,
    Electrify,
    Embargo,
    Encore,
    Entrainment,
    FairyLock,
    ForcedSwitch,
    Foresight,
    ForestsCurse,
    GuardSplit,
    GuardSwap,
    HealBlock,
    HealPulse,
    HeartSwap,
    Imprison,
    Instruct,
    LeechSeed,
    MagicPowder,
    MeFirst,
    Memento,
    MindReader,
    MiracleEye,
    Nightmare,
    PartingShot,
    PerishSong,
    Powder,
    PowerSplit,
    PowerSwap,
    PsychoShift,
    PsychUp,
    Quash,
    ReflectType,
    RolePlay,
    SimpleBeam,
    SkillSwap,
    Snatch,
    Soak,
    SpeedSwap,
    Spite,
    StrengthSap,
    SuppressAbility,
    Taunt,
    Teatime,
    Telekinesis,
    TopsyTurvy,
    Torment,
    ToxicThread,
    Trap,
    Trick,
    TrickOrTreat,
    WorrySeed,
    Yawn,
    //Direct damage
    Direct20,
    Direct40,
    DirectLevel,
    Psywave,
    SuperFang,
    //Recoil
    Recoil25,
    Recoil33,
    Recoil50,
    Recoil25Max,
    Recoil50Max,
    Crash50Max,
    AxeKick,
    VoltTackle,
    FlareBlitz,
    //Other added effects
    Absorb50,
    Absorb75,
    Absorb100,
    BreakScreens,
    ClearStats,
    CoreEnforcer,
    CureBurn,
    FakeOut,
    Feint,
    FirstImpression,
    FlameBurst,
    Flinch,
    HappyHour,
    KnockOff,
    PayDay,
    RapidSpin,
    SecretPower,
    SmackDown,
    SmellingSalts,
    Thief,
    ThousandArrows,
    WakeUpSlap,
    //Unique attack types
    AlwaysCrit,
    Assurance,
    AuraWheel,
    BeatUp,
    Belch,
    BodyPress,
    BurnUp,
    ChargingAttack,
    ContinuousDamage,
    Counter,
    DragonDarts,
    DreamEater,
    EchoedVoice,
    EerieSpell,
    Endeavor,
    ExpandingForce,
    FalseSwipe,
    FellStinger,
    FinalGambit,
    Fling,
    FlyingPress,
    FuryCutter,
    FutureSight,
    GlaiveRush,
    GrassyGlide,
    HiddenPower,
    IceSpinner,
    IgnoreAbility,
    Incinerate,
    IgnoreDefenseStage,
    JawLock,
    Judgement,
    LastResort,
    LastRespects,
    MetalBurst,
    MeteorBeam,
    MistyExplosion,
    MortalSpin,
    MultiAttack,
    NaturalGift,
    NaturePower,
    OHKO,
    OrderUp,
    PainSplit,
    PhotonGeyser,
    Pluck,
    PollenPuff,
    Poltergeist,
    Psyshock,
    Rage,
    Recharge,
    RevelationDance,
    Rollout,
    Round,
    SaltCure,
    SelfDestruct,
    ShellSideArm,
    SnipeShot,
    Snore,
    SpectralThief,
    SteelRoller,
    SuckerPunch,
    SwitchHit,
    Synchronoise,
    TechnoBlast,
    TeraBlast,
    Thrash,
    ThroatChop,
    Uproar,
    //Z-Moves
    ZMove,
    ZMoveSpecific,
    SplinteredStormshards,
    GuardianOfAlola,
    GenesisSupernova,
    ZMoveIgnoreAbility,
    LightThatBurnsTheSky,
    ClangorousSoulblaze,
    //Moves that double in power under certain conditions
    Acrobatics,
    BarbBarrage,
    BoltBeak,
    Brine,
    BurningJealousy,
    DynamaxCannon,
    Facade,
    FreezeDry,
    Hex,
    InfernalParade,
    LashOut,
    Payback,
    Pursuit,
    Retaliate,
    Revenge,
    RisingVoltage,
    StompingTantrum,
    TerrainPulse,
    Venoshock,
    WeatherBall,
    //Moves with unique power calcs
    WeightPower,
    RelativeWeightPower,
    HealthPower,
    Reversal,
    TargetHealthPower,
    LowSpeedPower,
    HighSpeedPower,
    UserStatPower,
    TargetStatPower,
    Return,
    Frustration,
    Magnitude,
    Present,
    TrumpCard,
    FoulPlay,
    //Paired effects
    Bide,
    BideHit,
    Stockpile,
    Swallow,
    SpitUp,
    FocusPunchWindup,
    FocusPunchAttack,
    SkyDrop,
    SkyDropHit,
    Pledge,
    Rainbow,
    Swamp,
    BurningField,
    FusionFlare,
    FusionBolt,
    BeakBlastWindup,
    ShellTrapSet,
    ShellTrapAttack,
    //Terrain effects
    ElectricTerrain,
    GrassyTerrain,
    MistyTerrain,
    PsychicTerrain,
    //Field effects
    AuroraVeil,
    Gravity,
    Haze,
    IonDeluge,
    LightScreen,
    LuckyChant,
    MagicRoom,
    Mist,
    MudSport,
    Reflect,
    Safeguard,
    StealthRock,
    Spikes,
    StickyWeb,
    Tailwind,
    ToxicSpikes,
    TrickRoom,
    WaterSport,
    Weather,
    WonderRoom,
    //Self-targeting effects
    Assist,
    BatonPass,
    Camouflage,
    Conversion,
    Conversion2,
    Copycat,
    DestinyBond,
    Grudge,
    HealingWish,
    LaserFocus,
    MagnetRise,
    Metronome,
    Mimic,
    MirrorMove,
    PowerTrick,
    Recycle,
    SleepTalk,
    StuffCheeks,
    Substitute,
    Teleport,
    Transform,
    Sketch,
    //Healing effects
    AquaRing,
    FloralHealing,
    Ingrain,
    Heal25,
    Heal50,
    HealBell,
    HealStatus,
    HealWeather,
    JungleHealing,
    LunarBlessing,
    Purify,
    Rest,
    RevivalBlessing,
    Roost,
    ShoreUp,
    TakeHeart,
    Wish,
    //Protection effects
    BanefulBunker,
    CraftyShield,
    Endure,
    KingsShield,
    MagicCoat,
    MatBlock,
    MaxGuard,
    Obstruct,
    Protect,
    QuickGuard,
    SpikyShield,
    WideGuard,
    SilkTrap,
    //Effects for doubles/triples
    AllySwitch,
    FollowMe,
    HelpingHand,
    RagePowder,
    Spotlight,
    //Max moves
    MaxMove,
    GMaxIgnoreAbilities,
    GMaxBreakProtection,
}

public static class MoveEffectUtils
{

    public static bool IsStatDrop(this MoveEffect effect)
        => effect is AttackDown1 or AttackDown2 or DefenseDown1
        or DefenseDown2 or SpAtkDown1 or SpAtkDown2 or SpDefDown1
        or SpDefDown2 or SpeedDown1 or SpeedDown2 or AttackDefenseDown1
        or DefenseSpDefDown1 or Captivate or TripleArrows or SpicyExtract;

    public static bool IsStatusMove(this MoveEffect effect)
        => effect is Paralyze or Freeze or Burn or Sleep or Poison or Toxic
        or TriAttack or DireClaw or BarbBarrage or InfernalParade;

    public static bool IsStatRaise(this MoveEffect effect)
        => effect is AttackUp1 or AttackUp2 or DefenseUp1 or DefenseUp2
        or DefenseUp3 or SpAtkUp1 or SpAtkUp2 or SpAtkUp2 or SpAtkUp3
        or SpDefUp2 or SpeedUp1 or SpeedUp2 or EvasionUp1
        or EvasionUp2 or CritRateUp2 or AttackAccuracyUp1
        or AttackDefenseUp1 or AttackDefenseAccUp1 or SpAtkSpDefUp1
        or AttackDefenseSpeedUp1 or SpAtkSpDefSpeedUp1 or AllUp1 or AllUp2
        or Autotomize or Acupressure or TakeHeart
        or BellyDrum or Charge or DefenseCurl or Growth or Minimize or OrderUp or SpicyExtract;

    public static bool IsShieldDustAffected(this MoveEffect effect)
    {
        return effect.IsStatusMove() || effect.IsStatDrop()
            || effect is Flinch;
    }

    public static bool IsSheerForceAffectedNotSelfOnly(this MoveEffect effect)
    {
        return effect.IsStatusMove() || effect.IsStatDrop()
            || effect is Flinch or Trap or Confuse or SmackDown or ThousandArrows or
            Curse or Nightmare or PerishSong or LeechSeed or Telekinesis or
            Yawn or Disable or Embargo or HealBlock or FellStinger or AxeKick;
    }

    public static bool IsSheerForceAffectedSelfOnly(this MoveEffect effect) =>
        effect.IsStatRaise() || effect is StealthRock or Spikes;

    public static bool HasRecoil(this MoveEffect effect)
        => effect is Recoil25 or Recoil33 or Recoil50 or Crash50Max;
}