public enum MoveID
{
    None,
    Pound,
    KarateChop,
    DoubleSlap,
    CometPunch,
    MegaPunch,
    PayDay,
    FirePunch,
    IcePunch,
    ThunderPunch,
    Scratch,
    ViseGrip,
    Guillotine,
    RazorWind,
    SwordsDance,
    Cut,
    Gust,
    WingAttack,
    Whirlwind,
    Fly,
    Bind,
    Slam,
    VineWhip,
    Stomp,
    DoubleKick,
    MegaKick,
    JumpKick,
    RollingKick,
    SandAttack,
    Headbutt,
    HornAttack,
    FuryAttack,
    HornDrill,
    Tackle,
    BodySlam,
    Wrap,
    TakeDown,
    Thrash,
    DoubleEdge,
    TailWhip,
    PoisonSting,
    Twineedle,
    PinMissile,
    Leer,
    Bite,
    Growl,
    Roar,
    Sing,
    Supersonic,
    SonicBoom,
    Disable,
    Acid,
    Ember,
    Flamethrower,
    Mist,
    WaterGun,
    HydroPump,
    Surf,
    IceBeam,
    Blizzard,
    Psybeam,
    BubbleBeam,
    AuroraBeam,
    HyperBeam,
    Peck,
    DrillPeck,
    Submission,
    LowKick,
    Counter,
    SeismicToss,
    Strength,
    Absorb,
    MegaDrain,
    LeechSeed,
    Growth,
    RazorLeaf,
    SolarBeam,
    PoisonPowder,
    StunSpore,
    SleepPowder,
    PetalDance,
    StringShot,
    DragonRage,
    FireSpin,
    ThunderShock,
    Thunderbolt,
    ThunderWave,
    Thunder,
    RockThrow,
    Earthquake,
    Fissure,
    Dig,
    Toxic,
    Confusion,
    Psychic,
    Hypnosis,
    Meditate,
    Agility,
    QuickAttack,
    Rage,
    Teleport,
    NightShade,
    Mimic,
    Screech,
    DoubleTeam,
    Recover,
    Harden,
    Minimize,
    Smokescreen,
    ConfuseRay,
    Withdraw,
    DefenseCurl,
    Barrier,
    LightScreen,
    Haze,
    Reflect,
    FocusEnergy,
    Bide,
    Metronome,
    MirrorMove,
    SelfDestruct,
    EggBomb,
    Lick,
    Smog,
    Sludge,
    BoneClub,
    FireBlast,
    Waterfall,
    Clamp,
    Swift,
    SkullBash,
    SpikeCannon,
    Constrict,
    Amnesia,
    Kinesis,
    SoftBoiled,
    HighJumpKick,
    Glare,
    DreamEater,
    PoisonGas,
    Barrage,
    LeechLife,
    LovelyKiss,
    SkyAttack,
    Transform,
    Bubble,
    DizzyPunch,
    Spore,
    Flash,
    Psywave,
    Splash,
    AcidArmor,
    Crabhammer,
    Explosion,
    FurySwipes,
    Bonemerang,
    Rest,
    RockSlide,
    HyperFang,
    Sharpen,
    Conversion,
    TriAttack,
    SuperFang,
    Slash,
    Substitute,
    Struggle,

    //Gen 2
    Sketch,
    TripleKick,
    Thief,
    SpiderWeb,
    MindReader,
    Nightmare,
    FlameWheel,
    Snore,
    Curse,
    Flail,
    Conversion2,
    Aeroblast,
    CottonSpore,
    Reversal,
    Spite,
    PowderSnow,
    Protect,
    MachPunch,
    ScaryFace,
    FeintAttack,
    SweetKiss,
    BellyDrum,
    SludgeBomb,
    MudSlap,
    Octazooka,
    Spikes,
    ZapCannon,
    Foresight,
    DestinyBond,
    PerishSong,
    IcyWind,
    Detect,
    BoneRush,
    LockOn,
    Outrage,
    Sandstorm,
    GigaDrain,
    Endure,
    Charm,
    Rollout,
    FalseSwipe,
    Swagger,
    MilkDrink,
    Spark,
    FuryCutter,
    SteelWing,
    MeanLook,
    Attract,
    SleepTalk,
    HealBell,
    Return,
    Present,
    Frustration,
    Safeguard,
    PainSplit,
    SacredFire,
    Magnitude,
    DynamicPunch,
    Megahorn,
    DragonBreath,
    BatonPass,
    Encore,
    Pursuit,
    RapidSpin,
    SweetScent,
    IronTail,
    MetalClaw,
    VitalThrow,
    MorningSun,
    Synthesis,
    Moonlight,
    HiddenPower,
    CrossChop,
    Twister,
    RainDance,
    SunnyDay,
    Crunch,
    MirrorCoat,
    PsychUp,
    ExtremeSpeed,
    AncientPower,
    ShadowBall,
    FutureSight,
    RockSmash,
    Whirlpool,
    BeatUp,

    //Gen 3
    FakeOut,
    Uproar,
    Stockpile,
    SpitUp,
    Swallow,
    HeatWave,
    Hail,
    Torment,
    Flatter,
    WillOWisp,
    Memento,
    Facade,
    FocusPunch,
    SmellingSalts,
    FollowMe,
    NaturePower,
    Charge,
    Taunt,
    HelpingHand,
    Trick,
    RolePlay,
    Wish,
    Assist,
    Ingrain,
    Superpower,
    MagicCoat,
    Recycle,
    Revenge,
    BrickBreak,
    Yawn,
    KnockOff,
    Endeavor,
    Eruption,
    SkillSwap,
    Imprison,
    Refresh,
    Grudge,
    Snatch,
    SecretPower,
    Dive,
    ArmThrust,
    Camouflage,
    TailGlow,
    LusterPurge,
    MistBall,
    FeatherDance,
    TeeterDance,
    BlazeKick,
    MudSport,
    IceBall,
    NeedleArm,
    SlackOff,
    HyperVoice,
    PoisonFang,
    CrushClaw,
    BlastBurn,
    HydroCannon,
    MeteorMash,
    Astonish,
    WeatherBall,
    Aromatherapy,
    FakeTears,
    AirCutter,
    Overheat,
    OdorSleuth,
    RockTomb,
    SilverWind,
    MetalSound,
    GrassWhistle,
    Tickle,
    CosmicPower,
    WaterSpout,
    SignalBeam,
    ShadowPunch,
    Extrasensory,
    SkyUppercut,
    SandTomb,
    SheerCold,
    MuddyWater,
    BulletSeed,
    AerialAce,
    IcicleSpear,
    IronDefense,
    Block,
    Howl,
    DragonClaw,
    FrenzyPlant,
    BulkUp,
    Bounce,
    MudShot,
    PoisonTail,
    Covet,
    VoltTackle,
    MagicalLeaf,
    WaterSport,
    CalmMind,
    LeafBlade,
    DragonDance,
    RockBlast,
    ShockWave,
    WaterPulse,
    DoomDesire,
    PsychoBoost,

    //Gen 4
    Roost,
    Gravity,
    MiracleEye,
    WakeUpSlap,
    HammerArm,
    GyroBall,
    HealingWish,
    Brine,
    NaturalGift,
    Feint,
    Pluck,
    Tailwind,
    Acupressure,
    MetalBurst,
    UTurn,
    CloseCombat,
    Payback,
    Assurance,
    Embargo,
    Fling,
    PsychoShift,
    TrumpCard,
    HealBlock,
    WringOut,
    PowerTrick,
    GastroAcid,
    LuckyChant,
    MeFirst,
    Copycat,
    PowerSwap,
    GuardSwap,
    Punishment,
    LastResort,
    WorrySeed,
    SuckerPunch,
    ToxicSpikes,
    HeartSwap,
    AquaRing,
    MagnetRise,
    FlareBlitz,
    ForcePalm,
    AuraSphere,
    RockPolish,
    PoisonJab,
    DarkPulse,
    NightSlash,
    AquaTail,
    SeedBomb,
    AirSlash,
    XScissor,
    BugBuzz,
    DragonPulse,
    DragonRush,
    PowerGem,
    DrainPunch,
    VacuumWave,
    FocusBlast,
    EnergyBall,
    BraveBird,
    EarthPower,
    Switcheroo,
    GigaImpact,
    NastyPlot,
    BulletPunch,
    Avalanche,
    IceShard,
    ShadowClaw,
    ThunderFang,
    IceFang,
    FireFang,
    ShadowSneak,
    MudBomb,
    PsychoCut,
    ZenHeadbutt,
    MirrorShot,
    FlashCannon,
    RockClimb,
    Defog,
    TrickRoom,
    DracoMeteor,
    Discharge,
    LavaPlume,
    LeafStorm,
    PowerWhip,
    RockWrecker,
    CrossPoison,
    GunkShot,
    IronHead,
    MagnetBomb,
    StoneEdge,
    Captivate,
    StealthRock,
    GrassKnot,
    Chatter,
    Judgment,
    BugBite,
    ChargeBeam,
    WoodHammer,
    AquaJet,
    AttackOrder,
    DefendOrder,
    HealOrder,
    HeadSmash,
    DoubleHit,
    RoarOfTime,
    SpacialRend,
    LunarDance,
    CrushGrip,
    MagmaStorm,
    DarkVoid,
    SeedFlare,
    OminousWind,
    ShadowForce,

    //Gen 5
    HoneClaws,
    WideGuard,
    GuardSplit,
    PowerSplit,
    WonderRoom,
    Psyshock,
    Venoshock,
    Autotomize,
    RagePowder,
    Telekinesis,
    MagicRoom,
    SmackDown,
    StormThrow,
    FlameBurst,
    SludgeWave,
    QuiverDance,
    HeavySlam,
    Synchronoise,
    ElectroBall,
    Soak,
    FlameCharge,
    Coil,
    LowSweep,
    AcidSpray,
    FoulPlay,
    SimpleBeam,
    Entrainment,
    AfterYou,
    Round,
    EchoedVoice,
    ChipAway,
    ClearSmog,
    StoredPower,
    QuickGuard,
    AllySwitch,
    Scald,
    ShellSmash,
    HealPulse,
    Hex,
    SkyDrop,
    ShiftGear,
    CircleThrow,
    Incinerate,
    Quash,
    Acrobatics,
    ReflectType,
    Retaliate,
    FinalGambit,
    Bestow,
    Inferno,
    WaterPledge,
    FirePledge,
    GrassPledge,
    VoltSwitch,
    StruggleBug,
    Bulldoze,
    FrostBreath,
    DragonTail,
    WorkUp,
    Electroweb,
    WildCharge,
    DrillRun,
    DualChop,
    HeartStamp,
    HornLeech,
    SacredSword,
    RazorShell,
    HeatCrash,
    LeafTornado,
    Steamroller,
    CottonGuard,
    NightDaze,
    Psystrike,
    TailSlap,
    Hurricane,
    HeadCharge,
    GearGrind,
    SearingShot,
    TechnoBlast,
    RelicSong,
    SecretSword,
    Glaciate,
    BoltStrike,
    BlueFlare,
    FieryDance,
    FreezeShock,
    IceBurn,
    Snarl,
    IcicleCrash,
    VCreate,
    FusionFlare,
    FusionBolt,

    //Gen 6
    FlyingPress,
    MatBlock,
    Belch,
    Rototiller,
    StickyWeb,
    FellStinger,
    PhantomForce,
    TrickOrTreat,
    NobleRoar,
    IonDeluge,
    ParabolicCharge,
    ForestsCurse,
    PetalBlizzard,
    FreezeDry,
    DisarmingVoice,
    PartingShot,
    TopsyTurvy,
    DrainingKiss,
    CraftyShield,
    FlowerShield,
    GrassyTerrain,
    MistyTerrain,
    Electrify,
    PlayRough,
    FairyWind,
    Moonblast,
    Boomburst,
    FairyLock,
    KingsShield,
    PlayNice,
    Confide,
    DiamondStorm,
    SteamEruption,
    HyperspaceHole,
    WaterShuriken,
    MysticalFire,
    SpikyShield,
    AromaticMist,
    EerieImpulse,
    VenomDrench,
    Powder,
    Geomancy,
    MagneticFlux,
    HappyHour,
    ElectricTerrain,
    DazzlingGleam,
    Celebrate,
    HoldHands,
    BabyDollEyes,
    Nuzzle,
    HoldBack,
    Infestation,
    PowerUpPunch,
    OblivionWing,
    ThousandArrows,
    ThousandWaves,
    LandsWrath,
    LightOfRuin,
    OriginPulse,
    PrecipiceBlades,
    DragonAscent,
    HyperspaceFury,

    //Gen 7
    BreakneckBlitzPhysical,
    BreakneckBlitzSpecial,
    AllOutPummelingPhysical,
    AllOutPummelingSpecial,
    SupersonicSkystrikePhysical,
    SupersonicSkystrikeSpecial,
    AcidDownpourPhysical,
    AcidDownpourSpecial,
    TectonicRagePhysical,
    TectonicRageSpecial,
    ContinentalCrushPhysical,
    ContinentalCrushSpecial,
    SavageSpinOutPhysical,
    SavageSpinOutSpecial,
    NeverEndingNightmarePhysical,
    NeverEndingNightmareSpecial,
    CorkscrewCrashPhysical,
    CorkscrewCrashSpecial,
    InfernoOverdrivePhysical,
    InfernoOverdriveSpecial,
    HydroVortexPhysical,
    HydroVortexSpecial,
    BloomDoomPhysical,
    BloomDoomSpecial,
    GigavoltHavocPhysical,
    GigavoltHavocSpecial,
    ShatteredPsychePhysical,
    ShatteredPsycheSpecial,
    SubzeroSlammerPhysical,
    SubzeroSlammerSpecial,
    DevastatingDrakePhysical,
    DevastatingDrakeSpecial,
    BlackHoleEclipsePhysical,
    BlackHoleEclipseSpecial,
    TwinkleTacklePhysical,
    TwinkleTackleSpecial,
    Catastropika,
    ShoreUp,
    FirstImpression,
    BanefulBunker,
    SpiritShackle,
    DarkestLariat,
    SparklingAria,
    IceHammer,
    FloralHealing,
    HighHorsepower,
    StrengthSap,
    SolarBlade,
    Leafage,
    Spotlight,
    ToxicThread,
    LaserFocus,
    GearUp,
    ThroatChop,
    PollenPuff,
    AnchorShot,
    PsychicTerrain,
    Lunge,
    FireLash,
    PowerTrip,
    BurnUp,
    SpeedSwap,
    SmartStrike,
    Purify,
    RevelationDance,
    CoreEnforcer,
    TropKick,
    Instruct,
    BeakBlast,
    ClangingScales,
    DragonHammer,
    BrutalSwing,
    AuroraVeil,
    SinisterArrowRaid,
    MaliciousMoonsault,
    OceanicOperetta,
    GuardianOfAlola,
    SoulStealingSevenStarStrike,
    StokedSparksurfer,
    PulverizingPancake,
    ExtremeEvoboost,
    GenesisSupernova,
    ShellTrap,
    FleurCannon,
    PsychicFangs,
    StompingTantrum,
    ShadowBone,
    Accelerock,
    Liquidation,
    PrismaticLaser,
    SpectralThief,
    SunsteelStrike,
    MoongeistBeam,
    TearfulLook,
    ZingZap,
    NaturesMadness,
    MultiAttack,
    TenMillionVoltThunderbolt,
    MindBlown,
    PlasmaFists,
    PhotonGeyser,
    LightThatBurnsTheSky,
    SearingSunrazeSmash,
    MenacingMoonrazeMaelstrom,
    LetsSnuggleForever,
    SplinteredStormshards,
    ClangorousSoulblaze,
    ZippyZap,
    SplishySplash,
    FloatyFall,
    PikaPapow,
    BouncyBubble,
    BuzzyBuzz,
    SizzlySlide,
    GlitzyGlow,
    BaddyBad,
    SappySeed,
    FreezyFrost,
    SparklySwirl,
    VeeveeVolley,
    DoubleIronBash,

    // Gen 8
    MaxGuard,
    DynamaxCannon,
    SnipeShot,
    JawLock,
    StuffCheeks,
    NoRetreat,
    TarShot,
    MagicPowder,
    DragonDarts,
    Teatime,
    Octolock,
    BoltBeak,
    FishiousRend,
    CourtChange,
    MaxFlare,
    MaxFlutterby,
    MaxLightning,
    MaxStrike,
    MaxKnuckle,
    MaxPhantasm,
    MaxHailstorm,
    MaxOoze,
    MaxGeyser,
    MaxAirstream,
    MaxStarfall,
    MaxWyrmwind,
    MaxMindstorm,
    MaxRockfall,
    MaxQuake,
    MaxDarkness,
    MaxOvergrowth,
    MaxSteelspike,
    ClangorousSoul,
    BodyPress,
    Decorate,
    DrumBeating,
    SnapTrap,
    PyroBall,
    BehemothBlade,
    BehemothBash,
    AuraWheel,
    BreakingSwipe,
    BranchPoke,
    Overdrive,
    AppleAcid,
    GravApple,
    SpiritBreak,
    StrangeSteam,
    LifeDew,
    Obstruct,
    FalseSurrender,
    MeteorAssault,
    Eternabeam,
    SteelBeam,
    ExpandingForce,
    SteelRoller,
    ScaleShot,
    MeteorBeam,
    ShellSideArm,
    MistyExplosion,
    GrassyGlide,
    RisingVoltage,
    TerrainPulse,
    SkitterSmack,
    BurningJealousy,
    LashOut,
    Poltergeist,
    CorrosiveGas,
    Coaching,
    FlipTurn,
    TripleAxel,
    DualWingbeat,
    ScorchingSands,
    JungleHealing,
    WickedBlow,
    SurgingStrikes,
    ThunderCage,
    DragonEnergy,
    FreezingGlare,
    FieryWrath,
    ThunderousKick,
    GlacialLance,
    AstralBarrage,
    EerieSpell,

    DireClaw,
    PsyshieldBash,
    PowerShift,
    StoneAxe,
    SpringtideStorm,
    MysticalPower,
    RagingFury,
    WaveCrash,
    Chloroblast,
    MountainGale,
    VictoryDance,
    HeadlongRush,
    BarbBarrage,
    EsperWing,
    BitterMalice,
    Shelter,
    TripleArrows,
    InfernalParade,
    CeaselessEdge,
    BleakwindStorm,
    WildboltStorm,
    SandsearStorm,
    LunarBlessing,
    TakeHeart,

    //Gen 9
    TeraBlast,
    SilkTrap,
    AxeKick,
    LastRespects,
    LuminaCrash,
    OrderUp,
    JetPunch,
    SpicyExtract,
    SpinOut,
    PopulationBomb,
    IceSpinner,
    GlaiveRush,
    RevivalBlessing,
    SaltCure,
    TripleDive,
    MortalSpin,

    //G-max Moves

    GMaxWildfire,
    GMaxBefuddle,
    GMaxVoltCrash,
    GMaxGoldRush,
    GMaxChiStrike,
    GMaxTerror,
    GMaxResonance,
    GMaxCuddle,
    GMaxReplenish,
    GMaxMalodor,
    GMaxStonesurge,
    GMaxWindRage,
    GMaxStunShock,
    GMaxFinale,
    GMaxDepletion,
    GMaxGravitas,
    GMaxVolcalith,
    GMaxSandblast,
    GMaxSnooze,
    GMaxTartness,
    GMaxSweetness,
    GMaxSmite,
    GMaxSteelsurge,
    GMaxMeltdown,
    GMaxFoamBurst,
    GMaxCentinferno,
    GMaxVineLash,
    GMaxCannonade,
    GMaxDrumSolo,
    GMaxFireball,
    GMaxHydrosnipe,
    GMaxOneBlow,
    GMaxRapidFlow,

    //Nonstandard moves

    ConfusionHit,
    Recharge,
    RazorWindAttack,
    DigAttack,
    FlyAttack,
    SolarBeamAttack,
    SkyAttackAttack,
    SkullBashAttack,
    BideMiddle,
    BideAttack,
    FocusPunchAttack,
    DiveAttack,
    BounceAttack,
    ShadowForceAttack,
    SkyDropAttack,
    RainbowPledge,
    SwampPledge,
    BurningFieldPledge,
    FreezeShockAttack,
    IceBurnAttack,
    PhantomForceAttack,
    GeomancyExecution,
    SolarBladeAttack,
    PollenPuffHeal,
    BeakBlastAttack,
    ShellTrapAttack,
    MeteorBeamAttack,

    Count,

    //Fake moves

    NonGhostCurse,

    //Non-moves

    Switch,
    UseItem,

    StandardCount = ConfusionHit - 1,
}

public static class MoveUtils
{
    public static ref MoveData Data(this MoveID move) => ref Move.MoveTable[(int)move];
    public static bool TriageAffected(this MoveID move) =>
        move.Data().effect is MoveEffect.Heal50 or MoveEffect.Absorb50
        or MoveEffect.HealingWish or MoveEffect.DreamEater or MoveEffect.HealWeather
        or MoveEffect.Roost or MoveEffect.Swallow or MoveEffect.Rest;
    public static bool SheerForceAffected(this MoveID move) =>
        move.Data().moveFlags.HasFlag(MoveFlags.effectOnSelfOnly) ?
        move.Data().effect.IsSheerForceAffectedSelfOnly() :
        move.Data().effect.IsSheerForceAffectedNotSelfOnly();
    //Todo: update Triage for Gen 5+ moves
    public static int ForewarnPower(this MoveID move) =>
        (move.Data().power, move.Data().effect) switch
        {
            (1, MoveEffect.HealthPower or MoveEffect.OHKO) => 150,
            (1, MoveEffect.Counter or MoveEffect.MetalBurst) => 120,
            (1, _) => 80,
            (_, _) => move.Data().power
        };
    public static MoveID MaxMove(this MoveID move, Pokemon mon)
    {
        if (move.Data().power is 0) return MoveID.MaxGuard;
        if (mon.gMaxFactor)
        {
            switch (mon.species)
            {
                case SpeciesID.Venusaur when move.Data().type is Type.Grass: return MoveID.GMaxVineLash;
                case SpeciesID.Charizard when move.Data().type is Type.Fire: return MoveID.GMaxWildfire;
                case SpeciesID.Blastoise when move.Data().type is Type.Water: return MoveID.GMaxCannonade;
                case SpeciesID.Butterfree when move.Data().type is Type.Bug: return MoveID.GMaxBefuddle;
                case SpeciesID.Pikachu when move.Data().type is Type.Electric: return MoveID.GMaxVoltCrash;
                case SpeciesID.Meowth when move.Data().type is Type.Normal: return MoveID.GMaxGoldRush;
                case SpeciesID.Machamp when move.Data().type is Type.Fighting: return MoveID.GMaxChiStrike;
                case SpeciesID.Gengar when move.Data().type is Type.Ghost: return MoveID.GMaxTerror;
                case SpeciesID.Kingler when move.Data().type is Type.Water: return MoveID.GMaxFoamBurst;
                case SpeciesID.Lapras when move.Data().type is Type.Ice: return MoveID.GMaxResonance;
                case SpeciesID.Eevee when move.Data().type is Type.Normal: return MoveID.GMaxCuddle;
                case SpeciesID.Snorlax when move.Data().type is Type.Normal: return MoveID.GMaxReplenish;
                case SpeciesID.Garbodor when move.Data().type is Type.Poison: return MoveID.GMaxMalodor;
                case SpeciesID.Melmetal when move.Data().type is Type.Steel: return MoveID.GMaxMeltdown;
                case SpeciesID.Rillaboom when move.Data().type is Type.Grass: return MoveID.GMaxDrumSolo;
                case SpeciesID.Cinderace when move.Data().type is Type.Fire: return MoveID.GMaxFireball;
                case SpeciesID.Inteleon when move.Data().type is Type.Water: return MoveID.GMaxHydrosnipe;
                case SpeciesID.Corviknight when move.Data().type is Type.Flying: return MoveID.GMaxWindRage;
                case SpeciesID.Orbeetle when move.Data().type is Type.Psychic: return MoveID.GMaxGravitas;
                case SpeciesID.Drednaw when move.Data().type is Type.Water: return MoveID.GMaxStonesurge;
                case SpeciesID.Coalossal when move.Data().type is Type.Rock: return MoveID.GMaxVolcalith;
                case SpeciesID.Flapple when move.Data().type is Type.Grass: return MoveID.GMaxTartness;
                case SpeciesID.Appletun when move.Data().type is Type.Grass: return MoveID.GMaxSweetness;
                case SpeciesID.Sandaconda when move.Data().type is Type.Ground: return MoveID.GMaxSandblast;
                case SpeciesID.Toxtricity or SpeciesID.ToxtricityLowKey when move.Data().type is Type.Electric: return MoveID.GMaxStunShock;
                case SpeciesID.Centiskorch when move.Data().type is Type.Fire: return MoveID.GMaxCentinferno;
                case SpeciesID.Hatterene when move.Data().type is Type.Fairy: return MoveID.GMaxSmite;
                case SpeciesID.Grimmsnarl when move.Data().type is Type.Dark: return MoveID.GMaxSnooze;
                case SpeciesID.Alcremie when move.Data().type is Type.Fairy: return MoveID.GMaxFinale;
                case SpeciesID.Copperajah when move.Data().type is Type.Steel: return MoveID.GMaxSteelsurge;
                case SpeciesID.Duraludon when move.Data().type is Type.Dragon: return MoveID.GMaxDepletion;
                case SpeciesID.Urshifu when move.Data().type is Type.Dark: return MoveID.GMaxOneBlow;
                case SpeciesID.UrshifuRapid when move.Data().type is Type.Water: return MoveID.GMaxRapidFlow;
                default: break;
            }
        }
        return move.Data().type switch
        {
            Type.Normal => MoveID.MaxStrike,
            Type.Fire => MoveID.MaxFlare,
            Type.Water => MoveID.MaxGeyser,
            Type.Grass => MoveID.MaxOvergrowth,
            Type.Electric => MoveID.MaxLightning,
            Type.Ice => MoveID.MaxHailstorm,
            Type.Ground => MoveID.MaxQuake,
            Type.Fighting => MoveID.MaxKnuckle,
            Type.Poison => MoveID.MaxOoze,
            Type.Flying => MoveID.MaxAirstream,
            Type.Bug => MoveID.MaxFlutterby,
            Type.Rock => MoveID.MaxRockfall,
            Type.Psychic => MoveID.MaxMindstorm,
            Type.Ghost => MoveID.MaxPhantasm,
            Type.Dragon => MoveID.MaxWyrmwind,
            Type.Dark => MoveID.MaxDarkness,
            Type.Steel => MoveID.MaxSteelspike,
            Type.Fairy => MoveID.MaxStarfall,
            Type.Typeless => MoveID.None,
            _ => MoveID.None,
        };
    }
}